# $FreeBSD$

PORTNAME=	mocha-on-bacon
PORTVERSION=	0.2.3
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	A Mocha adapter for Bacon, because it's yummy

LICENSE=	MIT

RUN_DEPENDS=	rubygem-mocha>=0.13:devel/rubygem-mocha

USES=		gem
NO_ARCH=	yes
USE_RUBY=	yes

.include <bsd.port.mk>
