# $FreeBSD$

PORTNAME=	terminal-notifier-guard
PORTVERSION=	1.7.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Send User Notifications on Mac OS X 10.8 - with status icons

LICENSE=	MIT

RUN_DEPENDS=	rubygem-bacon>=0:devel/rubygem-bacon \
		rubygem-mocha>=0:devel/rubygem-mocha \
		rubygem-mocha-on-bacon>=0:devel/rubygem-mocha-on-bacon \
		rubygem-rake>=0:devel/rubygem-rake

USES=		gem
NO_ARCH=	yes
USE_RUBY=	yes

.include <bsd.port.mk>
