# $FreeBSD$

PORTNAME=	line_notify
PORTVERSION=	1.0.1
CATEGORIES=	net rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Client for the LINE notify API

LICENSE=	MIT

BUILD_DEPENDS=	rubygem-bundler>1.16:sysutils/rubygem-bundler \
		rubygem-coveralls>=0:devel/rubygem-coveralls \
		rubygem-ffi>=1.9.18:devel/rubygem-ffi \
		rubygem-guard>=0:sysutils/rubygem-guard \
		rubygem-guard-rspec>=0:sysutils/rubygem-guard-rspec \
		rubygem-pry>=0:devel/rubygem-pry  \
		rubygem-rake>10:devel/rubygem-rake \
		rubygem-rspec>3:devel/rubygem-rspec \
		rubygem-terminal-notifier>=0:devel/rubygem-terminal-notifier \
		rubygem-terminal-notifier-guard>=0:devel/rubygem-terminal-notifier-guard

USES=		gem
NO_ARCH=	yes
USE_RUBY=	yes

.include <bsd.port.mk>
