# $FreeBSD$

PORTNAME=	ruby_http_client
PORTVERSION=	3.5.1
CATEGORIES=	www rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Quickly and easily access any RESTful or RESTful-like API.

LICENSE=	MIT

BUILD_DEPENDS=	rubygem-codecov>=0:devel/rubygem-codecov \
		rubygem-minitest>=5.9<6:devel/rubygem-minitest \
		rubygem-rake>=0:devel/rubygem-rake \
		rubygem-rubocop>=0.88.0:devel/rubygem-rubocop \
		rubygem-simplecov>=0.18.5:devel/rubygem-simplecov

NO_ARCH=	yes
USE_RUBY=	yes
USES=		gem

.include <bsd.port.mk>
