# $FreeBSD$

PORTNAME=	terminal-notifier
PORTVERSION=	2.0.0
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	ruby@FreeBSD.org
COMMENT=	Send User Notifications on macOS 10.10 or higher

LICENSE=	MIT

RUN_DEPENDS=	rubygem-bacon>=0:devel/rubygem-bacon \
		rubygem-mocha>=0:devel/rubygem-mocha \
		rubygem-mocha-on-bacon>=0:devel/rubygem-mocha-on-bacon

USES=		gem
NO_ARCH=	yes
USE_RUBY=	yes

.include <bsd.port.mk>
